### ISSUE TITLE
Need test accounts

### ISSUE THREAD

**Issue by jynxmagic** [advanced-web-project-group-9/Advanced-web-project#4]
Need some test account email and passwords (not real password!) from you guys

**Comment by Spamford** [comment]
email: samlord666@gmail.com
password: Password123

**Comment by Gawain112** [comment]
Email: Shane.Hawkins100@gmail.com
Password: Password1234

**Comment by jynxmagic** [comment]
email: ccarr895@gmail.com
password: password
